### ISSUE TITLE
Implementation of HTTPS connection to the server

### ISSUE THREAD

**Issue by cvejoski** [OpenRoberta/robertalab-usbprogram#7]
change the connection to the server from http to https.

**Comment by gregorsamsa183** [comment]
usbprogram structure has been changed in order to be compatible with java 1.6 because of Mac OS X requirements. However, Java 1.6 doesn't support HTTPS methods, so for now, https connection is not provided for connecting to the server. We should be able to find a way to use https connection if possible. Modifying the program structure to provide this only for non-OS X machines might be a non-generic solution.

**Comment by boonto** [comment]
This is already implemented.
